name: captable
services:
  app:
    build:
      target: deps
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: captable-app
    depends_on:
      - pg
      - smtp
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ".env"
    environment:
      - CI=true
      - UPLOAD_STORAGE_PATH=/app/uploads
    working_dir: /app
    command: [/bin/sh, -c, "rm -rf .next && pnpm install && pnpm dev"]
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.pnpm-store
      - uploads:/app/uploads

  studio:
    build:
      target: deps
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: captable-studio
    depends_on:
      - pg
      - smtp
    restart: always
    ports:
      - 5555:5555
    env_file:
      - ".env"
    environment:
      - CI=true
    working_dir: /app
    command: [/bin/sh, -c, "rm -rf .next && pnpm install && pnpm db:studio"]
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.pnpm-store
      - uploads:/app/uploads

  pg:
    image: postgres:15
    container_name: captable-database
    environment:
      - POSTGRES_USER=captable
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=captable
      - POSTGRES_EXTENSIONS=pgcrypto
    ports:
      - 54321:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  smtp:
    image: axllent/mailpit
    container_name: captable-smtp
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  postgres:
  uploads:
